### ISSUE TITLE
Snippet: DebuffAuraAnchor

### ISSUE THREAD

**Issue by skmzarn** [Krealle/Cell-Snippets#2]
Thank you so much for this snippet. I love it, however, I noticed it somewhat bugs abit. All of a sudden, you don't see the tooltips at all, or they will be back to default location. My guess is that this occurs when there is a bleed effect active, because it looks like your snippet does not like bleeds - or I am just being mistaken about that totally. I get no LUA errors.

Thanks again and please keep up the great work!

(I wrote a message in Discord, but thought it's better to make a ticket here instead, so I removed it.)

**Comment by Krealle** [comment]
Interesting, I'll take a look at it once I get the time - you only experience this with bleeds?

**Comment by skmzarn** [comment]
No, I noticed that it can happen without the bleeds, so apparently it doesn't seem to have anything to do with specifically bleeds. But I am not sure if it's because of your snippet, or if it's the addon itself. It would be cool if you can check it out atleast.
